version: '3'
services:
    
    app:
        build: ./Dockerfiles/app
        command: bash -c "pipenv install --system && python manage.py runserver 0.0.0.0:8000 "
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
    
    db:
        image: mysql:5.7
        ports:
            - '8806:3306'
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        volumes:
            - ./:/app
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            TZ: Europe/Moscow
            network_mode: bridge
        restart: always
    
